version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plant_disease_api
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      # Automatically open CORS for Amplify frontend connection later
      - CORS_ORIGINS=*
